# Generated by Django 3.1.3 on 2022-09-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=20)),
                ('pw', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AircraftType',
            fields=[
                ('no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('seats', models.IntegerField()),
                ('mfr', models.CharField(max_length=20)),
                ('seat_row', models.CharField(max_length=10)),
                ('seat_column', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'aircraft_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=10)),
                ('gate', models.IntegerField()),
            ],
            options={
                'db_table': 'airports',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'departments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FlightSchedule',
            fields=[
                ('no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('departure_date', models.DateField()),
                ('arrival_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('remain_seats', models.IntegerField()),
                ('gate_number', models.IntegerField()),
            ],
            options={
                'db_table': 'flight_schedule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inform',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inform',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InformCategory',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'inform_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('no', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=10)),
                ('id', models.CharField(max_length=20)),
                ('pw', models.CharField(max_length=30)),
                ('gender', models.IntegerField()),
                ('birth_date', models.DateField()),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=20)),
                ('security1', models.CharField(blank=True, max_length=10, null=True)),
                ('security2', models.CharField(blank=True, max_length=10, null=True)),
                ('sms', models.IntegerField()),
                ('country_code', models.IntegerField()),
                ('check_foreign', models.IntegerField()),
                ('passport', models.CharField(blank=True, max_length=30, null=True)),
                ('p_points', models.IntegerField()),
            ],
            options={
                'db_table': 'member',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PassengerForm',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('seat', models.CharField(blank=True, max_length=10, null=True)),
                ('check_in', models.IntegerField()),
            ],
            options={
                'db_table': 'passenger_form',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PassengerInfo',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('info_collect', models.IntegerField()),
                ('nationality', models.IntegerField()),
                ('rule_agree', models.IntegerField()),
                ('danger_agree', models.IntegerField()),
            ],
            options={
                'db_table': 'passenger_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'points',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Qna',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('date', models.DateField(blank=True, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'qna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QnaCategory',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'qna_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('re_no', models.CharField(blank=True, max_length=20, null=True)),
                ('flight_no', models.CharField(max_length=20)),
                ('fare_type', models.IntegerField()),
                ('baggage_check', models.IntegerField()),
            ],
            options={
                'db_table': 'reservation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('points', models.IntegerField()),
            ],
            options={
                'db_table': 'route',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('method', models.IntegerField()),
                ('card_number', models.CharField(blank=True, max_length=20, null=True)),
                ('account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'transaction',
                'managed': False,
            },
        ),
    ]
