# Generated by Django 3.1.3 on 2022-09-14 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_admin_aircrafttype_airports_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_au'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='AircraftType',
        ),
        migrations.DeleteModel(
            name='Airports',
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='Departments',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='FlightSchedule',
        ),
        migrations.DeleteModel(
            name='Inform',
        ),
        migrations.DeleteModel(
            name='InformCategory',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='PassengerForm',
        ),
        migrations.DeleteModel(
            name='PassengerInfo',
        ),
        migrations.DeleteModel(
            name='Points',
        ),
        migrations.DeleteModel(
            name='Qna',
        ),
        migrations.DeleteModel(
            name='QnaCategory',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
